services:
  db:
    container_name: db
    build: ./backend/internal/db
    image: dating_app/db
    ports:
      - "3306:3306"
    env_file: ./backend/.env

  api:
    container_name: api
    build: ./backend
    image: dating_app/api
    ports:
      - "8080:8080"
    env_file: ./backend/.env
    depends_on:
      - db
    environment:
      DBHOST: db
